name: go-encryptor
base: core18 # the base snap is the execution environment for this snap
version: "1.0.2"
summary: A Simple A file encryptor
description: |
  go-encryptor is created to be as simple as possible to help you
   encrypt and decrypt files.

grade: stable
confinement: strict

apps:
  go-encryptor:
    command: go-encryptor

parts:
  go-encryptor:
    plugin: go
    source: .
    go-importpath: go-encryptor

plugs:
  go-encryptor-home:
    interface: home
  go-encryptor-removable-media:
    interface: removable-media
